name: Checks
on:
  push:
    branches:
    - master
  pull_request:

jobs:
  gitlocalize-bug-checking:
    name: Checking Gitlocalize bugs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.2.0
      with:
        fetch-depth: 200
    - uses: funkill/bug-check-action@master
      with:
        translation-dir: second-edition-ru/src
        original-dir: second-edition/src
